[package]
name = "fungible-token"
version = "1.0.0"
authors = ["Near Inc <duonghb53@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.7"
near-contract-standards = "4.0.0-pre.7"
